package com.bank.payment.orchestration.domain;

public enum PaymentStatus {
    RECEIVED, TRANSLATED, QUALIFYING, ENRICHED, WAREHOUSED, MOP_DERIVED,
    IN_REPAIR, PROCESSING, PARTNER_APPROVED, PARTNER_REJECTED,
    CLEARING_SUBMITTED, CLEARED, FAILED, COMPLETED,
    REVERSAL_IN_PROGRESS, REVERSED, REVERSAL_FAILED
}
